### ISSUE TITLE
TA feedback for hw03

### ISSUE THREAD

**Issue by wvictor14** [STAT545-UBC-hw-2019-20/stat545-hw-realseanla#7]
Hi Sean,

You're report is concise and everything is laid out nicely. So it was very easy to follow your work! I appreciate that.

I think you could spend more time interpreting your plots and what they are actually showing. Some of your comments don't really follow from your analysis. Here are some examples:

 **Task 2:** 
>  ..Let’s visualize the minimum, maximum, and range of the GDP per capita for each continent.

And then a boxplot is shown, but is this all a boxplot is showing? After all, you already showed us these things with the table, so why is a boxplot complementary for this task?

**Task 3:**
> It seems that Oceania and Europe have the **greatest GDP per capita distribution**, which are both skewed to the right.

What does this mean, "greatest GDP per capita distribution"? You're right though, about the skew.

**Task 4:**
>...it seems that Oceania has the highest life expectancy and lowest standard deviation, whereas Africa has the lowest mean life expectancy and (at least one of the largest) standard deviations.

But the plot shown does not just show a single value of mean / standard deviation of life expectancy for each continent?

**Comment by sean-la** [comment]
Hi Victor,

Thank you for the helpful feedback!

I agree with almost all of your comments, but there is one thing I'd like to talk about regarding my task 4 submission. 

I understand that task 4 asks for a computation of some sort of modified mean. I did compute the regular mean in my submission, but I also computed the standard deviations for each year and for each continent, and plotted the standard deviations as confidence intervals. I interpretted my computation of mean AND standard deviation as something different from vanilla mean, because that gives us more context of the spread of the life expectancies of each continent. I don't have much background in public health, so I didn't want to compute something like a mean weighted by population, which is something that I don't understand.

**Comment by wvictor14** [comment]
Hi Sean,

Unfortunately, a standard deviation is not considered a different type of mean.  Yes, it does give us an idea of the spread.

The references to the "trimmed mean" and "weighted mean" were just some examples of what a modified mean could look like. I can sympathize that these terms may be unfamiliar to those without a background in statistics (I certainly don't have one either!), but that's why we have set up the discussion repo and office hours -- for students to ask questions about the assignments that they are unsure about.

**Comment by sean-la** [comment]
I see, thank you!
